=== swapnilkumarrai/Basic-Python-Game-And-Projects/JsonSchemaValidation/json_schema.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "properties": {"study_id": {"type": "string","minLength": 1, 
"maxLength": 50}, "block_type": {"type": "string", "oneOf":[{"pattern": "^[A-Z]"}, {"pattern": "^[a-z]"}], "enum": ["CHECKBOX"]}, 
"sequence": {"type": "integer","minimum": 1, "exclusiveMinimum":0, "maximum":10, "exclusiveMaximum":11}, "block_properties": {"type": "object", 
"properties": {"question": {"type": "string"}, "options": {"type": "array", "items": {"type": "object", "properties": {"option_text": 
{"type": "string"}, "option_id": {"type": "string"}}, "required": ["option_text"]}, "minItems": 1, "maxItems":4, "uniqueItems": true, 
"additionalItems":false}, "response_required": {"type": "boolean"}, "randomize": {"type": "boolean"}, "none_of_the_above": {"type": "boolean"}, 
"others": {"type": "boolean"}, "all_of_the_above": {"type": "boolean"}}, "maxProperties":15, "minProperties":1, 
"required": ["all_of_the_above", "none_of_the_above", "options", "others", "question", "randomize", "response_required"]}}, 
"required": ["block_properties", "block_type", "sequence", "study_id"]}

=== swapnilkumarrai/Basic-Python-Game-And-Projects/JsonSchemaValidation/Sample_json_data.json
{

    "study_id": "d2f7b331-db81-4df3-bea6-e33cc8c74153",

    "block_type": "CHECKBOX",

    "sequence": 1,

    "block_properties": {

        "question": "is this a CHECKBOX question?",

        "options": [

            {"option_text": "option one", "option_id": ""},

            {"option_text": "option two", "option_id": ""},

            {"option_text": "option three"}

        ],

        "response_required": false,

        "randomize": true,

        "none_of_the_above": false,

        "others": false,

        "all_of_the_above": false

    }

}
